name: 'Check branch progress'
description: 'Checks the progress pf branch on Crowdin'
inputs:
  project-id:
    description: 'Project identifier from Crowdin'
    required: true
  branch-id:
    description: 'Branch name to get the correct branch in Crowdin'
    required: true
  personal-token:
    description: 'Personal token from Crowdin to perform API request'
    required: true
outputs:
  branch-name:
    description: "Branch name from Crowdin API"
    value: ${{ steps.branch-progress.outputs.branch-name }}
  is-ready:
    description: "Indicator if branch is ready to download translations"
    value: ${{ steps.branch-progress-bash.outputs.is-ready }}
runs:
  using: 'composite'
  steps:
    - run: |
        ./.github/actions/check-crowdin-branch-progress/check-progress.sh \
          -p ${{ inputs.project-id }} \
          -b ${{ inputs.branch-id }} \
          -t ${{ inputs.personal-token }}
      id: branch-progress
      shell: bash
