name: Crowdin Synchronization

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
    paths:
      - 'localization/en-SG.translation.json'
  repository_dispatch:
    types: [crowdin]

permissions:
  contents: read

concurrency:
  group: PR-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  TERM: dumb
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  CROWDIN_PROJECT_ID: 573871

jobs:
  upload-sources:
    name: Upload new source file to version branch on Crowdin
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.merged }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1

      - name: Extract branch name and format
        id: format-branch
        uses: ./.github/actions/format-branch-name
        with:
          format-type: 'crowdin'
          branch-name: ${{ github.head_ref }}

      - name: Upload new source
        if: steps.format-branch.outputs.formatted-branch != ''
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: true
          crowdin_branch_name: ${{ steps.format-branch.outputs.formatted-branch }}
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

  download-translations:
    name: Download new translations from Crowdin
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'repository_dispatch' }}
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1

      - name: Check client payload
        run: echo ${{ github.event.client_payload.branchId }}

      - name: Get branch name from Crowdin
        uses: ./.github/actions/get-crowdin-branch-name
        id: get-branch-name
        with:
          branch-id: ${{ github.event.client_payload.branchId }}
          project-id: ${{ env.CROWDIN_PROJECT_ID }}
          personal-token: ${{ secrets.CROWDIN_TOKEN }}

      - name: Format branch name
        id: format-branch
        if: steps.get-branch-name.outputs.branch-name != ''
        uses: ./.github/actions/format-branch-name
        with:
          format-type: 'github'
          branch-name: ${{ steps.get-branch-name.outputs.branch-name }}

      - name: Download translations
        if: steps.format-branch.outputs.formatted-branch != ''
        uses: crowdin/github-action@v1
        with:
          upload_sources: false
          download_translations: true
          localization_branch_name: ${{ steps.format-branch.outputs.localization-branch }}
          crowdin_branch_name: ${{ steps.get-branch-name.outputs.branch-name }}
          config: 'crowdin.yml'
          pull_request_base_branch_name: ${{ steps.format-branch.outputs.formatted-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

  upload-and-delete:
    name: Upload latest sources to the main branch on Crowdin and delete the old one
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1


      - name: Upload new source
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: true
          crowdin_branch_name: 'development'
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Extract branch name and format
        id: format-branch
        uses: ./.github/actions/format-branch-name
        with:
          format-type: 'crowdin'
          branch-name: ${{ github.head_ref }}

      - name: Delete branch in crowdin
        uses: ./.github/actions/delete-branch-crowdin
        with:
          branch-name: ${{ steps.format-branch.outputs.formatted-branch }}
          project-id: ${{ env.CROWDIN_PROJECT_ID }}
          personal-token: ${{ secrets.CROWDIN_TOKEN }}
