name: Crowdin Synchronization

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main
  repository_dispatch:
    types: [crowdin]

permissions:
  contents: read

concurrency:
  group: PR-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  TERM: dumb
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  CROWDIN_PROJECT_ID: 573871

jobs:
  upload-sources:
    name: Upload new source file to version branch on Crowdin
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1

      - name: Extract branch name and format
        id: format-branch
        shell: bash
        run: |
          BRANCH=${{ github.head_ref }}
          FORMATTED_BRANCH=${BRANCH//\//-}
          echo "branch=$FORMATTED_BRANCH" >> $GITHUB_OUTPUT

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            source:
              - localization/en-SG.translation.json

      - name: Upload new source
        if: steps.changed-files.outputs.source_any_changed == 'true'
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: true
          crowdin_branch_name: ${{ steps.format-branch.outputs.branch }}
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

  download-translations:
    name: Download new translations from Crowdin
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'repository_dispatch' }}
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1

      - name: Check client payload
        run: echo ${{ github.event.client_payload.branchId }}

      - name: Check branch progress on Crowdin
        uses: ./.github/actions/check-crowdin-branch-progress
        with:
          branch-id: ${{ github.event.client_payload.branchId }}
          project-id: ${{ env.CROWDIN_PROJECT_ID }}
          personal-token: 5a10c8997dbe5a7783cc15bcf6ee98cd2660360c2db5dc515825527d344b329df2a6e8e486284110

      - name: Extract branch name and format
        id: format-branch
        shell: bash
        run: |
          BRANCH=${{ github.head_ref }}
          FORMATTED_BRANCH=${BRANCH//\//-}
          echo "branch=$FORMATTED_BRANCH" >> $GITHUB_OUTPUT

      - name: Download translations
        run: "echo ${{ steps.branch-progress.outputs.progress }}"
        # if: ${{ steps.branch-progress.outputs.progress == '100' }}
#         uses: crowdin/github-action@v1
  #         with:
  #           download_translations: true
  #           crowdin_branch_name: ${{ steps.format-branch.outputs.branch }}
  #           config: 'crowdin.yml'
  #           pull_request_base_branch_name: ${{ github.event.pull_request.head.ref }}
  #         env:
  #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #           CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
  #           CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

  upload-and-delete:
    name: Upload latest sources to the main branch on Crowdin and delete the old one
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Check branch name
      #   uses: propertyguru/mobile/actions/branch@v3.0.1

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            source:
              - localization/en-SG.translation.json

      - name: Upload new source
        if: steps.changed-files.outputs.source_any_changed == 'true'
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: true
          auto_approve_imported: true
          import_eq_suggestions: true
          crowdin_branch_name: 'development'
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

      - name: Extract branch name and format
        id: format-branch
        shell: bash
        run: |
          BRANCH=${{ github.head_ref }}
          FORMATTED_BRANCH=${BRANCH//\//-}
          echo "branch=$FORMATTED_BRANCH" >> $GITHUB_OUTPUT

      - name: Delete branch in crowdin
        uses: ./.github/actions/delete-branch-crowdin
        if: steps.changed-files.outputs.source_any_changed == 'true'
        with:
          branch-name: ${{ steps.format-branch.outputs.branch }}
          project-id: ${{ env.CROWDIN_PROJECT_ID }}
          personal-token: ${{ secrets.CROWDIN_TOKEN }}
